apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-conf
  namespace: ase-p1g4
data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    listener 8080 0.0.0.0
    protocol websockets
    allow_anonymous true
